[project]
name = "graph-creator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.0",
    "fastapi-users>=15.0.3",
    "matplotlib>=3.10.8",
    "sqlalchemy>=2.0.45",
    "streamlit>=1.53.0",
]
